config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path(@flat)
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<h1>All our flats (<%= @flats.length %>)</h1>

<div class="flat-cards">
  <% @flats.each do |flat| %>
    <div class="flat-card">
      <div class="card-content">
        <h2><%= flat.name %></h2>
        <p><%= flat.address %></p>
        <i class="fas fa-user-friends"> <%= flat.number_of_guests %></i>
        <i class="fas fa-euro-sign"> <%= flat.price_per_night %></i>
      </div>
      <div class="link">
        <%= link_to "More info", flat_path(flat) %>
        <%= link_to "Edit", edit_flat_path(flat) %>
        <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>Add a new flat</h1>

<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h3><%= @flat.address %></h3>

<h2>A bit more about this flat...</h2>
<p><%= @flat.description %></p>

<h2>Details</h2>
<i class="fas fa-user-friends"> <%= @flat.number_of_guests %></i>
<i class="fas fa-euro-sign"> <%= @flat.price_per_night %></i>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="banner d-flex justify-content-between">
      <h3><%= link_to "Simple Airbnb", flats_path %></h3>
      <button class="btn .btn-default"><%= link_to "Add Flat", new_flat_path %></button>
    </div>
    <%= yield %>
  </body>
</html>